{% set name = "cutde" %}
{% set version = "23.6.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cutde-{{ version }}.tar.gz
  sha256: 946aeb03b3bf2f9060dabda1dd84330a67a7fddab27879010107382bcca31eac

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

  host:
    - python
    - pip
    - numpy
    - pybind11
    - mako

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyproj
    - pybind11
    - mako

test:
  imports:
    - cutde
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tbenthompson/cutde
  summary: 130 million TDEs per second, Python + CUDA TDEs from Nikkhoo and Walter 2015
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tbenthompson
